perf: implement concat-matmul in burn (#103)
We have nice gains shown in benches below (I didn't run the baseline
benches for inputs larger than `8x1024x1024` because they were too slow)
but there is an issue with running larger inputs (e.g.
`run-layers/concat_matmul/f32/8x8192x8192` and
`run-layers/concat_matmul/Element/8x8192x8192`), crashing with:

```sh
thread 'main' panicked at cubecl/crates/cubecl-runtime/src/client.rs:241:10:
called `Result::unwrap()` on an `Err` value: BufferTooBig(2147483648)
```

I'm looking into this. I found related
https://github.com/tracel-ai/burn/issues/3510, but this is reported only
for "autotune" feature. I did try running with autotune on and off and
hit this error in both cases.